services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - service-a
      - service-b

  service-a:
    build: ./service-a
    ports:
      - "5001:5001"

  service-b:
    build: ./service-b
    ports:
      - "5002:5002"
