version: '3.8'
services:
   proxy:
      build:
         context: .
         dockerfile: nginx/Dockerfile
   ports:
      - "80:80"
   depends_on:
      - service-a
      - service-b


service-a:
   build: ./service-a
   ports:
      - "3001:3001"


service-b:
   build: ./service-b
   ports:
      - "3002:3002"
